### ISSUE TITLE
Support for problems with multi colored holds

### ISSUE THREAD

**Issue by kasper-i** [jesper-solver/scoreboard#13]

**Comment by jesper-solver** [comment]
Might be able to do something with css gradients...

**Comment by kasper-i** [comment]
Or diagonal stripes like this article showcases: https://css-tricks.com/stripes-css/

**Comment by kasper-i** [comment]
I will add a secondary color to the data model next.

**Comment by kasper-i** [comment]
Backend updated so now the scorecard page can be updated as well.

**Comment by jesper-solver** [comment]
Currently blocked by the color problem - #29 needs to be resolved first!
