### ISSUE TITLE
Create and endpoint for resetting all contenders for a contest

### ISSUE THREAD

**Issue by jesper-solver** [jesper-solver/scoreboard#27]
URL: contest/[contestId]/resetContenders
Remove all ticks, and reset name, entered date etc.

Used when an organizer has "tested" a contest, and want's everything back to normal before the real contest begins.

**Comment by kasper-i** [comment]
We should probably also have a safety mechanism that prevents this action from being executed after the the contest has started.

**Comment by jesper-solver** [comment]
Good idea! All comp class start times must be in the future or something like that.
